teams_abv = {
    "4hands": "4HA",
    "BC Kosmodysk": "BCK",
    "Brave Beavers": "BBV",
    "Flow": "FLW",
    "Frisbnik": "FRI",
    "Grandmaster Flash": "GMF",
    "krakUF": "KRK",
    "KWR Knury": "KWR",
    "mJAH": "MJH",
    "RJP": "RJP",
    "Uwaga Pies": "UWG",
    "Zawierucha": "ZWR",
    "042": "042",
    "2obvious": "2OB",
    "71 Wratislavia": "71W",
    "Albatros": "ALB",
    "Czarna Kompania": "CZK",
    "Dysko Polot": "DPL",
    "Mad Hatters": "MHT",
    "Ohana": "OHN",
    "Szczupaki": "SZC",
    "Ultimatum": "ULT",
    "Wrocław Południe": "WRP",
    "#967": "967",
    "Kato Vice": "KVC",
    "Trójmiasto United": "3UN",
    "Tychy Claws": "TCH",
    "Ultimatum Szkwał": "ULS",
    "Ultimatum Sztorm": "ULT",
    
}

